apiVersion: v1
kind: Pod
metadata:
  name: busbox-pod
  labels:
    app: busbox
spec:
  containers:
    - name: busbox
      image: traefik:v3.7.13-nanoserver-ltsc2022
      ports:
        - containerPort: 80
